"""
Framingham Heart Study — Flask Deployment API
Steps 11-13 of the Project Guidelines

Endpoints:
  GET  /              → Health check (Lovable handles the frontend)
  POST /predict       → CHD risk classification
  POST /predict_glucose → Glucose regression
  GET  /health        → API health check
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import numpy as np
import os

app = Flask(__name__)
CORS(app)  # Allow Lovable frontend (different domain) to call this API

# ── Load saved models ────────────────────────────────────────────────────────
# These files are generated by your notebook's Phase 7 (Steps 31-32)
CLF_MODEL_PATH   = "best_clf_model.joblib"
CLF_SCALER_PATH  = "scaler_clf.joblib"
REG_MODEL_PATH   = "best_reg_model.joblib"
REG_SCALER_PATH  = "scaler_reg.joblib"

# Models that need scaled input (from your notebook's scaled_models set)
SCALED_CLF_MODELS = {'Logistic Regression', 'KNN', 'SVM', 'Naive Bayes', 'Neural Network'}
SCALED_REG_MODELS = {'Linear Regression', 'Ridge Regression', 'SVR', 'ANN Regressor'}

clf_model  = None
clf_scaler = None
reg_model  = None
reg_scaler = None
clf_name   = "Unknown"
reg_name   = "Unknown"

def load_models():
    global clf_model, clf_scaler, reg_model, reg_scaler
    try:
        clf_model  = joblib.load(CLF_MODEL_PATH)
        clf_scaler = joblib.load(CLF_SCALER_PATH)
        reg_model  = joblib.load(REG_MODEL_PATH)
        reg_scaler = joblib.load(REG_SCALER_PATH)
        print("✅ All models loaded successfully")
    except FileNotFoundError as e:
        print(f"⚠️  Model file not found: {e}")
        print("   Run the notebook first to generate .joblib files.")

load_models()

# ── Feature definitions (same order as X_clf / X_reg in your notebook) ──────
# Features: all columns except TenYearCHD and risk_label
CLF_FEATURES = [
    "male", "age", "education", "currentSmoker", "cigsPerDay",
    "BPMeds", "prevalentStroke", "prevalentHyp", "diabetes",
    "totChol", "sysBP", "diaBP", "BMI", "heartRate", "glucose"
]

# For regression target is glucose — same feature set minus glucose itself
REG_FEATURES = [
    "male", "age", "education", "currentSmoker", "cigsPerDay",
    "BPMeds", "prevalentStroke", "prevalentHyp", "diabetes",
    "totChol", "sysBP", "diaBP", "BMI", "heartRate", "TenYearCHD"
]


# ── Routes ───────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return jsonify({"api": "Framingham Heart Study ML API", "version": "1.0", "endpoints": ["/health", "/predict", "/predict_glucose"]})


@app.route("/health")
def health():
    return jsonify({
        "status": "ok",
        "clf_model_loaded": clf_model is not None,
        "reg_model_loaded": reg_model is not None,
    })


@app.route("/predict", methods=["POST"])
def predict():
    """CHD Risk Classification"""
    if clf_model is None:
        return jsonify({"error": "Classification model not loaded. Run the notebook first."}), 503

    data = request.get_json(force=True)

    try:
        features = np.array([[data[f] for f in CLF_FEATURES]], dtype=float)
    except KeyError as e:
        return jsonify({"error": f"Missing feature: {e}"}), 400

    # Determine if this model needs scaled input
    model_type = type(clf_model).__name__
    needs_scale = any(s.lower() in model_type.lower()
                      for s in ["Logistic", "KNeighbors", "SVC", "GaussianNB", "MLP"])

    X = clf_scaler.transform(features) if needs_scale else features

    prediction = int(clf_model.predict(X)[0])
    proba = clf_model.predict_proba(X)[0].tolist() if hasattr(clf_model, "predict_proba") else None

    label = "⚠️ CHD Risk" if prediction == 1 else "✅ No CHD Risk"
    confidence = round(max(proba) * 100, 1) if proba else None

    return jsonify({
        "prediction": prediction,
        "label": label,
        "confidence_pct": confidence,
        "probabilities": {"No Risk": round(proba[0]*100,1), "At Risk": round(proba[1]*100,1)} if proba else None
    })


@app.route("/predict_glucose", methods=["POST"])
def predict_glucose():
    """Glucose Regression"""
    if reg_model is None:
        return jsonify({"error": "Regression model not loaded. Run the notebook first."}), 503

    data = request.get_json(force=True)

    try:
        features = np.array([[data[f] for f in REG_FEATURES]], dtype=float)
    except KeyError as e:
        return jsonify({"error": f"Missing feature: {e}"}), 400

    model_type = type(reg_model).__name__
    needs_scale = any(s.lower() in model_type.lower()
                      for s in ["Linear", "Ridge", "SVR", "MLP"])

    X = reg_scaler.transform(features) if needs_scale else features
    glucose_pred = float(reg_model.predict(X)[0])

    return jsonify({
        "predicted_glucose": round(glucose_pred, 2),
        "unit": "mg/dL",
        "interpretation": (
            "Normal" if glucose_pred < 100
            else "Pre-diabetic" if glucose_pred < 126
            else "Diabetic range"
        )
    })


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
